# Generated by Django 5.2rc1 on 2025-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
